name: test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        containers: [ 1.17.1-bullseye ]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containers }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Unit Tests
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        run: go test -race -timeout=60s ./...
